sudo: required

language: php

php:
    - '7.1'

addons:
  apt:
    packages:
      - docker-ce

# Exclude feature branches (must be test by pull-requests)
branches:
  except:
    - /feature\/.*/

# Keep composer cache
cache:
  directories:
    - $HOME/.composer/cache

# Get only 20 last commits
git:
  depth: 20

install:
  - make install-prod

script:
  - make test-cs-fixer
  - make phpstan

notifications:
  email:
    on_success: change
    on_failure: always
