<?php

declare(strict_types=1);

namespace Stadline\LinkdataClient\src\Linkdata\Client;

use Doctrine\Common\Collections\ArrayCollection;
use Stadline\LinkdataClient\src\ClientHydra\Client\HydraClient;
use Stadline\LinkdataClient\src\ClientHydra\Exception\ClientHydraException;
use Stadline\LinkdataClient\src\Linkdata\Entity\Activity;
use Stadline\LinkdataClient\src\Linkdata\Entity\Sport;
use Stadline\LinkdataClient\src\Linkdata\Entity\Universe;

/**
 * @method Activity            getActivity(string $id, array $options = [])
 * @method ArrayCollection     getActivityDatastream(string $id, array $options = [])
 * @method ArrayCollection     getActivityLocations(string $id, array $options = [])
 * @method ArrayCollection     getActivities(array $options = [])
 * @method Activity            putActivity(Activity $activity, array $options = [])
 * @method Activity            postActivity(Activity $activity, array $options = [])
 * @method void                deleteActivity(string $id, array $options = [])
 * @method ActivityCalculation getActivityCalculation(string $id, array $options = [])
 * @method ArrayCollection     getActivityCalculations(array $options = [])
 * @method Brand               getBrand(string $id, array $options = [])
 * @method ArrayCollection     getBrands(array $options = [])
 * @method Connector           getConnector(string $id, array $options = [])
 * @method ArrayCollection     getConnectors(array $options = [])
 * @method Datatype            getDatatype(string $id, array $options = [])
 * @method ArrayCollection     getDatatypes(array $options = [])
 * @method DeviceModel         getDeviceModel(string $id, array $options = [])
 * @method ArrayCollection     getDeviceModels(array $options = [])
 * @method DeviceNotification  getDeviceNotification(string $id, array $options = [])
 * @method ArrayCollection     getDeviceNotifications(array $options = [])
 * @method DeviceNotification  putDeviceNotification(DeviceNotification $deviceNotification, array $options = [])
 * @method DeviceNotification  postDeviceNotification(DeviceNotification $deviceNotification, array $options = [])
 * @method void                deleteDeviceNotification(string $id, array $options = [])
 * @method Firmware            getFirmware(string $id, array $options = [])
 * @method ArrayCollection     getFirmwares(array $options = [])
 * @method GlobalChallenge     getGlobalChallenge(string $id, array $options = [])
 * @method ArrayCollection     getGlobalChallenges(array $options = [])
 * @method Job                 getJob(string $id, array $options = [])
 * @method ArrayCollection     getJobs(array $options = [])
 * @method Job                 putJob(Job $job, array $options = [])
 * @method Job                 getUser(Job $job, array $options = [])
 * @method ArrayCollection     getUsers(array $options = [])
 * @method ArrayCollection     getUserStat(string $id, array $options = [])
 * @method User                putUser(User $user, array $options = [])
 * @method User                postUser(User $user, array $options = [])
 * @method void                deleteUser(string $id, array $options = [])
 * @method PoiCategory         getPoiCategory(string $id, array $options = [])
 * @method ArrayCollection     getPoiCategories(array $options = [])
 * @method ShareActivity       getShareActivity(string $id, array $options = [])
 * @method ArrayCollection     getShareActivities(array $options = [])
 * @method ShareActivity       postShareActivity(ShareActivity $shareActivity, array $options = [])
 * @method void                deleteShareActivity(string $id, array $options = [])
 * @method ShareUser           getShareUser(string $id, array $options = [])
 * @method ArrayCollection     getShareUsers(array $options = [])
 * @method ShareUser           getShareUserStat(ShareUser $shareUser, array $options = [])
 * @method ShareUser           postShareUser(ShareUser $shareUser, array $options = [])
 * @method void                deleteShareUser(string $id, array $options = [])
 * @method Sport               getSport(string $id, array $options = [])
 * @method ArrayCollection     getSports(array $options = [])
 * @method StorageKey          getStorageKey(string $id, array $options = [])
 * @method ArrayCollection     getStorageKeys(array $options = [])
 * @method Universe            getUniverse(string $id, array $options = [])
 * @method ArrayCollection     getUniverses(array $options = [])
 * @method UserAgreement       getUserAgreement(string $id, array $options = [])
 * @method ArrayCollection     getUserAgreements(array $options = [])
 * @method UserAgreement       putUserAgreement(UserAgreement $userAgreement, array $options = [])
 * @method UserAgreement       postUserAgreement(UserAgreement $serAgreement, array $options = [])
 * @method UserDevice          getUserDevice(string $id, array $options = [])
 * @method ArrayCollection     getUserDevices(array $options = [])
 * @method UserDevice          putUserDevice(UserDevice $userDevice, array $options = [])
 * @method UserDevice          postUserDevice(UserDevice $userDevice, array $options = [])
 * @method void                deleteUserDevice(string $id, array $options = [])
 * @method UserMeasureGoal     getUserMeasureGoal(string $id, array $options = [])
 * @method ArrayCollection     getUserMeasureGoals(array $options = [])
 * @method UserMeasureGoal     putUserMeasureGoal(UserMeasureGoal $userMeasureGoal, array $options = [])
 * @method UserMeasureGoal     postUserMeasureGoal(UserMeasureGoal $userMeasureGoal, array $options = [])
 * @method void                deleteUserMeasureGoal(string $id, array $options = [])
 * @method UserMeasure         getUserMeasure(string $id, array $options = [])
 * @method ArrayCollection     getUserMeasures(array $options = [])
 * @method UserMeasure         putUserMeasure(UserMeasure $userMeasure, array $options = [])
 * @method UserMeasure         postUserMeasure(UserMeasure $userMeasure, array $options = [])
 * @method void                deleteUserMeasure(string $id, array $options = [])
 * @method UserPoi             getUserPoi(string $id, array $options = [])
 * @method ArrayCollection     getUserPois(array $options = [])
 * @method UserPoi             putUserPoi(UserPoi $userPoi, array $options = [])
 * @method UserPoi             postUserPoi(string $userPoi, array $options = [])
 * @method void                deleteUserPoi(string $id, array $options = [])
 * @method UserProgram         getUserProgram(string $id, array $options = [])
 * @method ArrayCollection     getUserPrograms(array $options = [])
 * @method UserProgram         putUserProgram(UserProgram $userProgram, array $options = [])
 * @method UserProgram         postUserProgram(UserProgram $userProgram, array $options = [])
 * @method void                deleteUserProgram(string $id, array $options = [])
 * @method UserRecord          getUserRecord(string $id, array $options = [])
 * @method ArrayCollection     getUserRecords(array $options = [])
 * @method UserRoute           getUserRoute(string $id, array $options = [])
 * @method ArrayCollection     getUserRoutes(array $options = [])
 * @method UserRoute           putUserRoute(UserRoute $userRoute, array $options = [])
 * @method UserRoute           postUserRoute(UserRoute $userRoute, array $options = [])
 * @method void                deleteUserRoute(string $id, array $options = [])
 * @method UserSession         getUserSession(string $id, array $options = [])
 * @method ArrayCollection     getUserSessions(array $options = [])
 * @method UserSession         putUserSession(UserSession $userSession, array $options = [])
 * @method UserSession         postUserSession(UserSession $userSession, array $options = [])
 * @method void                deleteUserSession(string $id, array $options = [])
 * @method UserStorage         getUserStorage(string $id, array $options = [])
 * @method ArrayCollection     getUserStorages(array $options = [])
 * @method UserStorage         putUserStorage(UserStorage $userStorage, array $options = [])
 * @method UserStorage         postUserStorage(UserStorage $userStorage, array $options = [])
 * @method void                deleteUserStorage(string $id, array $options = [])
 * @method UserSumup           getUserSumup(string $id, array $options = [])
 * @method ArrayCollection     getUserSumups(array $options = [])
 */
class LinkdataClient extends HydraClient
{
    /**
     * @throws ClientHydraException
     */
    public function __call(string $method, array $args)
    {
        return $this->send($method, $args);
    }
}
